name: Docker Image Build

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-frontend-dev:
    name: Build Frontend (Dev)
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/dev' || github.event.pull_request.head.ref == 'dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker image (Dev)
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL_DEV }} \
            -t w1-frontend-dev ./FE

  build-frontend-prod:
    name: Build Frontend (Prod)
    runs-on: ubuntu-latest
    environment: prod
    if: github.ref == 'refs/heads/main' || github.event.pull_request.head.ref == 'main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker image (Prod)
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL_PROD }} \
            -t w1-frontend-prod ./FE
